require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe RentalUnitsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # RentalUnit. As you add validations to RentalUnit, be sure to
  # adjust the attributes here as well.
  let(:user) { Fabricate :user }
  let(:valid_attributes) {
    {
      address: "LaBelle, FL",
      rooms: 3,
      bathrooms: 2,
      price_cents: 400,
      user_id: user.id
    }
  }

  let(:invalid_attributes) {
    {
      address: '',
      rooms: 3,
      bathrooms: 2,
      price_cents: 400,
      user_id: user.id
    }
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RentalUnitsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all rental_units as @rental_units" do
      rental_unit = RentalUnit.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:rental_units)).to eq([rental_unit])
    end
  end

  describe "GET #show" do
    it "assigns the requested rental_unit as @rental_unit" do
      rental_unit = RentalUnit.create! valid_attributes
      get :show, params: {id: rental_unit.to_param}, session: valid_session
      expect(assigns(:rental_unit)).to eq(rental_unit)
    end
  end

  describe "GET #new" do
    xit "assigns a new rental_unit as @rental_unit" do
      get :new, params: {}, session: valid_session
      expect(assigns(:rental_unit)).to be_a_new(RentalUnit)
    end
  end

  describe "GET #edit" do
    xit "assigns the requested rental_unit as @rental_unit" do
      rental_unit = RentalUnit.create! valid_attributes
      get :edit, params: {id: rental_unit.to_param}, session: valid_session
      expect(assigns(:rental_unit)).to eq(rental_unit)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new RentalUnit" do
        expect {
          post :create, params: {rental_unit: valid_attributes}, session: valid_session
        }.to change(RentalUnit, :count).by(1)
      end

      it "assigns a newly created rental_unit as @rental_unit" do
        post :create, params: {rental_unit: valid_attributes}, session: valid_session
        expect(assigns(:rental_unit)).to be_a(RentalUnit)
        expect(assigns(:rental_unit)).to be_persisted
      end

      xit "redirects to the created rental_unit" do
        post :create, params: {rental_unit: valid_attributes}, session: valid_session
        expect(response).to redirect_to(RentalUnit.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved rental_unit as @rental_unit" do
        post :create, params: {rental_unit: invalid_attributes}, session: valid_session
        expect(assigns(:rental_unit)).to be_a_new(RentalUnit)
      end

      xit "re-renders the 'new' template" do
        post :create, params: {rental_unit: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        {
          address: 'Address 2'
        }
      }

      it "updates the requested rental_unit" do
        rental_unit = RentalUnit.create! valid_attributes
        put :update, params: {id: rental_unit.to_param, rental_unit: new_attributes}, session: valid_session
        rental_unit.reload
        expect(rental_unit.address).to eq new_attributes[:address]
      end

      it "assigns the requested rental_unit as @rental_unit" do
        rental_unit = RentalUnit.create! valid_attributes
        put :update, params: {id: rental_unit.to_param, rental_unit: valid_attributes}, session: valid_session
        expect(assigns(:rental_unit)).to eq(rental_unit)
      end

      xit "redirects to the rental_unit" do
        rental_unit = RentalUnit.create! valid_attributes
        put :update, params: {id: rental_unit.to_param, rental_unit: valid_attributes}, session: valid_session
        expect(response).to redirect_to(rental_unit)
      end
    end

    context "with invalid params" do
      it "assigns the rental_unit as @rental_unit" do
        rental_unit = RentalUnit.create! valid_attributes
        put :update, params: {id: rental_unit.to_param, rental_unit: invalid_attributes}, session: valid_session
        expect(assigns(:rental_unit)).to eq(rental_unit)
      end

      xit "re-renders the 'edit' template" do
        rental_unit = RentalUnit.create! valid_attributes
        put :update, params: {id: rental_unit.to_param, rental_unit: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested rental_unit" do
      rental_unit = RentalUnit.create! valid_attributes
      expect {
        delete :destroy, params: {id: rental_unit.to_param}, session: valid_session
      }.to change(RentalUnit, :count).by(-1)
    end

    xit "redirects to the rental_units list" do
      rental_unit = RentalUnit.create! valid_attributes
      delete :destroy, params: {id: rental_unit.to_param}, session: valid_session
      expect(response).to redirect_to(rental_units_url)
    end
  end

end
